### ISSUE TITLE
Not compatible with myandroidtools pro

### ISSUE THREAD

**Issue by maz-1** [lj3lj3/XBridge#5]
myandroidtools pro version can be verified and enabled, but when i touch the icon from recents/notifications/info nothing happens at all.

**Comment by lj3lj3** [comment]
It's not the issues of XBridge, MyAndroidToolsPro does not add the XBridge support code, which is a broadcast receiver to start the right app details page. You can verify this by using the MyAndroidTools Pro to check the list of broadcast receiver of itself, it does not have the receiver of AppInfoReciver which free version of MyAndroidTools has. Try to talk to developer to add support code to the pro version too, thanks.
